#!/bin/bash

#Input & Varibles
read -p "SRA Accession Number: " SAMPLE
DATADIR=[(FILL IN APPROPRIATE DIRECTORY)
RED='\033[0;31m'
NC='\033[0m'
echo &
wait; echo "Variables: Done"

#Setting the module environment
module load bioinfo-tools sratools
echo "Module load: Done"

#Setting directory
cd $DATADIR
echo "Changing directory: Done"

#Prefetch:
echo &
wait; echo -e "${RED}Initate Prefetch${NC}" &
wait; prefetch -X 4000000000 $SAMPLE &
wait; echo "Download of" $SAMPLE ": Done" &
wait; echo &

#Fasterq-dump:
wait; echo &
wait; echo -e "${RED}Initiate Fasterq-dump${NC}" &
wait; fasterq-dump $SAMPLE.sra 
echo &
wait; echo "Conversion of" $SAMPLE ": Done" &
wait; echo &

#Compressing:
wait; echo &
wait; echo -e "${RED}Initiate Compressing${NC}" &
wait; tar -czvf $SAMPLE.tar.gz $SAMPLE.sra_1.fastq $SAMPLE.sra_2.fastq &
wait; echo &
wait; echo "Compression of" $SAMPLE ": Done" &
wait; echo &

#Deletion of old files:
wait; echo &
wait; echo -e "${RED}Initiate Removal${NC}" &
wait; rm $SAMPLE.sra* &
wait; echo "Removal of" $SAMPLE.sra "and" $SAMPLE.fastq": Done" &
wait; echo

wait; echo "Download of" $SAMPLE ": Done" &
wait; echo &

#Fasterq-dump:
wait; echo &
wait; echo -e "${RED}Initiate Fasterq-dump${NC}" &
wait; fasterq-dump $SAMPLE.sra 
echo &
wait; echo "Conversion of" $SAMPLE ": Done" &
wait; echo &

#Compressing:
wait; echo &
wait; echo -e "${RED}Initiate Compressing${NC}" &
wait; tar -czvf $SAMPLE.tar.gz $SAMPLE.sra_1.fastq $SAMPLE.sra_2.fastq &
wait; echo &
wait; echo "Compression of" $SAMPLE ": Done" &
wait; echo &

#Deletion of old files:
wait; echo &
wait; echo -e "${RED}Initiate Removal${NC}" &
wait; rm $SAMPLE.sra* &
